### ISSUE TITLE
Suggestion: Share Pictures as Journal Entries

### ISSUE THREAD

**Issue by Silenc42** [mech-tools/one-journal-handouts#2]
Hi!
I love the current functionality! There is a use-case that's very close to what this mod does, that comes up for me quite often.
I have an image I want to share and I want the players to be able to look it up themselves. E.g. the picture of an NPC which is part of a large journal entry in a module I bought. I can currently click on the picture and show it to my players, but they have no access to it later since it doesn't really exist as an object.

Idea: add the share button to the picture preview window. When clicked, it adds the picture as a journal page to a "shared pictures" (configurable) journal.
The process should be similar to the currently existing one, only with a different source. Instead of copyJournalPage it is rather createJournalPageFromImage.

**Comment by mech-tools** [comment]
Hi,

Thanks for the suggestion. After thinking about the idea, I think it's beyond the scope of this module.

This module is dedicated to handouts and not really to sharing images inserted in a text page. There are several reasons for this:
- If an image is to become a handout, it should have been a handout in the first place (and placed in a dedicated page).
- An image inserted in a text page has no title, and setting a default title would result in a long list of pages with the same title.
- A more advanced implementation that would suggest entering the page title when sharing an image would be outside the scope of this module.
- Your use case seems to be quite specific and I think it's better, in this case, to create a journal with all the images as handouts rather than finding an alternative to not having to do it.

I don't take the decision lightly, and this is the first time I've turned down a feature since I started creating modules.

I'm closing the ticket, but if you come up with a good idea that could solve the problem while staying within the scope of this module, I may consider reopening it.

**Comment by Silenc42** [comment]
Hi again!
No worries! I appreciate you taking the time to consider my suggestion. Thank you!
I understand your points and they make sense to me. I agree, this would be a scope extension, I merely hoped, it would be an acceptable one. Unfortunately, I am using a pre-made module where the creators, apparently, did not think of showing these images to players. I shall keep looking for an easy way to solve this.

As for an idea regarding the names/titles: I understand that entering a title would go against the core idea of this module; it is meant as a 1-click solution, if I understand correctly. My idea would be to use the filename without extension wherever a title in required. In my use-case, we are working with a pre-made adventure module and the filenames can be assumed as understandable enough.
Disclaimer: This is not meant to try and force the issue, merely in the spirit of discussion and sharing ideas.

Again, thank you for your consideration!
Cheers! :)

**Comment by mech-tools** [comment]
One thing tho. Is storing the images in a dedicated journal entry that players can reopen afterwards a requirement?

If not, you can simple display the image for a brief moment to the players or better yet use another module of mine: share-media (on mobile phone, don't have the link, but you can browse fvtt modules list to find it)

**Comment by Silenc42** [comment]
Yes, being re-openable is what I am looking for. Just showing them the image is possible with the built in "show players" button. My players asked to be able to look it up later by themselves.

**Comment by mech-tools** [comment]
Players and their demands!
